import './globals.css'
import Navbar from './components/Navbar'
import AuthContext from './context/AuthContext'
import ToasterContext from './context/ToasterContext'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  

  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ToasterContext/>
          <Navbar session = {session}/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
